- hosts: localhost
  gather_facts: false
  tasks:
  - name: mount image
    shell: losetup -P /dev/loop0 {{file}}
  - name: mount boot partition
    ansible.posix.mount:
      path: /mnt
      src: /dev/loop0p1
      fstype: vfat
      state: mounted
      fstab: /tmp/tmp.fstab
  - name: create ssh file
    ansible.builtin.copy:
      content: ''
      dest: /mnt/ssh
  - name: unmount boot partition
    ansible.posix.mount:
      path: /mnt
      state: unmounted
      fstab: /tmp/tmp.fstab
  - name: mount root partition
    ansible.posix.mount:
      path: /mnt
      src: /dev/loop0p2
      fstype: ext4
      state: mounted
      fstab: /tmp/tmp.fstab
  - name: create root ssh config dir
    ansible.builtin.file:
      path: /mnt/root/.ssh
      state: directory
      mode: 0700
      owner: root
      group: root
  - name: create root authorized keys file
    ansible.builtin.copy:
      src: "{{key}}"
      dest: /mnt/root/.ssh/authorized_keys
      mode: 0600
      owner: root
      group: root
  - name: create pi ssh config dir
    ansible.builtin.file:
      path: /mnt/home/pi/.ssh
      state: directory
      mode: 0700
      owner: '1000'
      group: '1000'
  - name: create pi authorized keys file
    ansible.builtin.copy:
      src: "{{key}}"
      dest: /mnt/home/pi/.ssh/authorized_keys
      mode: 0600
      owner: '1000'
      group: '1000'
  - name: set hostname
    ansible.builtin.copy:
      content: "{{host}}"
      dest: /mnt/etc/hostname
      mode: 0644
      owner: root
      group: root
  - name: unmount root partition
    ansible.posix.mount:
      path: /mnt
      state: unmounted
      fstab: /tmp/tmp.fstab
  - name: unmount image
    shell: losetup -d /dev/loop0

